### ISSUE TITLE
Extension crashes

### ISSUE THREAD

**Issue by fleadope** [asvetliakov/vscode-neovim#128]
I'm getting an error which crashes the extension on load: 

```
[exthost] [error] Error: nvim_ui_attach: No such UI option: ext_messages
	at /home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/neovim/lib/api/Base.js:31:28
	at Transport.parseMessage (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/neovim/lib/utils/transport.js:96:13)
	at DecodeStream.<anonymous> (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/neovim/lib/utils/transport.js:37:18)
	at DecodeStream.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at DecodeStream.Readable.push (_stream_readable.js:210:10)
	at DecodeStream.Transform.push (_stream_transform.js:150:32)
	at DecodeBuffer.DecodeStream.decoder.push (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
	at DecodeBuffer.flush (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)
	at DecodeStream._transform (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/msgpack-lite/lib/decode-stream.js:30:16)
	at DecodeStream.Transform._read (_stream_transform.js:189:10)
	at DecodeStream.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at DecodeStream.Writable.write (_stream_writable.js:301:11)
	at Buffered.ondata (_stream_readable.js:713:22)
	at Buffered.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Buffered.Readable.push (_stream_readable.js:210:10)
	at Buffered.Transform.push (_stream_transform.js:150:32)
	at Buffered.afterTransform (_stream_transform.js:94:10)
	at Buffered._transform (/home/lee/.vscode/extensions/asvetliakov.vscode-neovim-0.0.45/node_modules/neovim/lib/utils/buffered.js:29:24)
	at Buffered.Transform._read (_stream_transform.js:189:10)
	at Buffered.Transform._write (_stream_transform.js:177:12)
	at doWrite (_stream_writable.js:417:12)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Buffered.Writable.write (_stream_writable.js:301:11)
	at Socket.ondata (_stream_readable.js:713:22)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

I'm kind of a newb, let me know what other info I can give you to help troubleshoot....

**Comment by asvetliakov** [comment]
You need neovim 0.4+

**Comment by fleadope** [comment]
Thanks!
