### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by junkdeck** [asvetliakov/vscode-neovim#143]
For some reason it doesn't work at all on one of my machines. Pressing `:` doesn't show the output in the statusbar, hjkl doesn't move the cursor and I can't enter Insert mode.
It used to work and then it didn't.

I'm running Debian 10, using a `neovim 0.4.3` I've built from source with `RelWithDebInfo`, and specifying the output of `which nvim` in the configuration.

Did I mess something up during compilation of neovim?

**Comment by junkdeck** [comment]
okay so i ran `checkhealth` and there were some issues with the ruby provider that i solved - now i get the vim command line dropdown when i hit `:` and I can move around, but for some reason, vertical cursor movement skips a line. ???

**Comment by 3nuc** [comment]
You could try using this extension with the AppImage version of neovim to check if maybe something went wrong with building from source. You could also try running neovim without any plugins if you have any

**Comment by asvetliakov** [comment]
If you have `init.vim` try with empty one

>vertical cursor movement skips a line. ???

if line is wrapped, `j/k` skips the wrapped line, `gj/gk` takes into account wrapped lines

**Comment by makslevental** [comment]
i just installed on ubuntu 18 and i get this in the vscode extension host log

```
[2020-01-09 16:28:14.961] [exthost] [error] Activating extension asvetliakov.vscode-neovim failed due to an error:
[2020-01-09 16:28:14.961] [exthost] [error] Error: Error making request to nvim_ui_attach
	at NeovimClient.request (/home/maksim/.vscode/extensions/asvetliakov.vscode-neovim-0.0.47/node_modules/neovim/lib/api/Base.js:75:23)
	at NeovimClient.uiAttach (/home/maksim/.vscode/extensions/asvetliakov.vscode-neovim-0.0.47/node_modules/neovim/lib/api/Neovim.js:537:21)
	at NVIMPluginController.<anonymous> (/home/maksim/.vscode/extensions/asvetliakov.vscode-neovim-0.0.47/out/controller.js:1504:31)
	at Generator.next (<anonymous>)
	at fulfilled (/home/maksim/.vscode/extensions/asvetliakov.vscode-neovim-0.0.47/out/controller.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by RichardBronosky** [comment]
Can we get some diagnostic instructions, please?

I just installed neovim for the first time `brew install neovim` and this extension, specified `"vscode-neovim.neovimPath": "/usr/local/bin/nvim"` but I can see no effects. Not sure what to try next.

**Comment by mdoliwa** [comment]
Plugin page says "Neovim 0.5+ is required.". Had the same problem. when I installed version 0.5 and updated path settings all works fine now.

**Comment by asvetliakov** [comment]
Closing since it's not the extension issue

**Comment by idling-mind** [comment]
I made a mistake of setting the Neovim Executable path to `nvim-qt.exe` instead of `nvim.exe`. After the path was fixed and a restart, the extension started working fine.
