### ISSUE TITLE
Error making request to nvim_set_client_info when trying remote ssh

### ISSUE THREAD

**Issue by tanc** [asvetliakov/vscode-neovim#235]
I'm trying to open a remote session using the vscode extension `Remote - SSH` but getting an unhandled exception  `Error making request to nvim_set_client_info`

```
[11:08:55.192] > local-server> Spawned ssh: 59440
[11:08:55.197] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[11:08:55.236] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:qGcuQ5v7KOrXa/HhDmTMwR0U0sixdkaQQv/55prQxig
[11:08:55.281] stderr> Authenticated to 192.168.1.72 ([192.168.1.72]:22).
[11:09:12.060] Terminating local server
[11:09:12.062] Resolver error: Connecting with SSH timed out
[11:09:12.070] ------




[11:09:12.071] Local server exit: 15
[11:09:12.661] Unhandled rejection: Error: Error making request to nvim_set_client_info
	at NeovimClient.request (/Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/node_modules/neovim/lib/api/Base.js:75:23)
	at NeovimClient.setClientInfo (/Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/node_modules/neovim/lib/api/Neovim.js:600:14)
	at NVIMPluginController.<anonymous> (/Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/out/controller.js:1553:31)
	at Generator.next (<anonymous>)
	at /Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/out/controller.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/out/controller.js:4:12)
	at NVIMPluginController.init (/Users/tanc/.vscode/extensions/asvetliakov.vscode-neovim-0.0.50/out/controller.js:1546:16)
```

**Comment by tanc** [comment]
Possibly related: #225

**Comment by asvetliakov** [comment]
as stated in #225 remote neovim is not supported. and never be
