### ISSUE TITLE
pressing [ESC] freezes Neo Vim Plugin - Messegage from Log(Window)

### ISSUE THREAD

**Issue by thomas-repo** [asvetliakov/vscode-neovim#338]
Hi, 
I'm quite new to this Plugin, I have switched from the VIM plugin now to this Neo Vim plugin because I thought i would get more performance by being able to access the VIM Command line directly. 
Mehhhh, but somehow I always seem to crash the NeoVim Plugin when I hit Escape, after this event I can use the mouse to navigate but such things as text selection, etc. aren't possible anymore. Actually any navigation/movement with the keyboard within VSCode stopped working.

I found an error message, which appears instantly after hitting [ESC], within Log(Window) but honestly I don't know how to deal with that message.  
I hope someone is able to help me, or give me some hints were to search for a solution. 
Thanks 

> [2020-09-05 14:58:34.171] [renderer1] [error] Illegal value for `line`: Error: Illegal value for `line`
    at d._lineAt (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:478:822)
    at Object.lineAt (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:477:797)
    at Object.getEditorCursorPos (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/out/utils.js:263:34)
    at NVIMPluginController.applyRedrawUpdate (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/out/controller.js:1198:38)
    at NVIMPluginController.processRedrawBatch (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/out/controller.js:1175:18)
    at NeovimClient.NVIMPluginController.onNeovimNotification (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/out/controller.js:811:22)
    at NeovimClient.emit (events.js:203:13)
    at NeovimClient.EventEmitter.emit (domain.js:476:20)
    at NeovimClient.emitNotification (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/node_modules/neovim/lib/api/client.js:86:18)
    at NeovimClient.handleNotification (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/node_modules/neovim/lib/api/client.js:101:18)
    at Transport.emit (events.js:203:13)
    at Transport.EventEmitter.emit (domain.js:476:20)
    at Transport.parseMessage (/home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/node_modules/neovim/lib/utils/transport.js:116:18)
    at /home/monster/.vscode-oss/extensions/asvetliakov.vscode-neovim-0.0.52/node_modules/neovim/lib/utils/transport.js:77:26
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by asvetliakov** [comment]
need repro

**Comment by asvetliakov** [comment]
Can you try also the test version from #334 pull ?

**Comment by thomas-repo** [comment]
Ok, first of all THANKS, sure I'll have a try with your suggestions.

BUT what exactly do you mean with "need repro" (I guess I'm still a newbie)
and how do I change my plugin git-branch within VSCode from master to refactor branch?

**Comment by asvetliakov** [comment]
>BUT what exactly do you mean with "need repro"

Need reproduction steps

>and how do I change my plugin git-branch within VSCode from master to refactor branch?

Install version attached to the last message in the PR

**Comment by thomas-repo** [comment]
Ok, I'll have a try to be create some log. 
Setup:
* Installed VSCodium from the AUR - version 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0) x64
* otherwise virgin VSCodium besides Neo Vim Plugin installed from Microsoft Marketplace (version 0.0.52) seems like master-branch

Procedure for creating my error:
* created a new file / opened an existing (doesn't matter in regards)
* entered insert mode
* with / without entering something in insert mode (doesn't matter either)
* hitting [ESC] 
* and exactly in the moment of the keypress the attached error message appears and the Plugin seems to freeze. I cant move around with h,j,k,l, anymore etc.

.....as for the new version (0.0.60) I'll have a try later that day, is there any verbose log to catch whats actually happening after the keypress?

**Comment by asvetliakov** [comment]
For `0.0.60` there are log related settings in extension options

**Comment by asvetliakov** [comment]
Feel free to reopen if the problem still exists

**Comment by krzykli** [comment]
Hey folks,

Running into the same issue. Repro
- go into insert mode
- hit escape **twice**
Result: You will no longer be able to move around with hjkl

**VSCodium** Version: 1.54.3
**NVIM** v0.5.0-dev+1176-g9481310c2
**nvcode-neovim** v0.0.78

Thanks!

**Comment by Shatur95** [comment]
@krzykli, the problem is most likely in your configuration.

**Comment by sramekj** [comment]
I am experiencing the same issue as @krzykli (on VSCodium 1.62.54, nvcode-neovim v0.0.83, nvim 0.6.1). Haven't touched the configuration of the plugin (except for path to nvim.exe on w32). The freezes occur to me randomly but always when going from insert mode to the normal mode.
